# deploy.yml
name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:
        types: [synchronize]
    workflow_dispatch:

# Set the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

env:
    NODE_VERSION: 18.17.1
    GENERIC_LIBRARY: frontend/generic-library
    BASE_URL: ${{ secrets.BASE_URL }}

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: '📥 checkout repository'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: '🔄  Cache node_modules'
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-

            - name: '🔧  Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: '🔧 Install npm@latest'
              run: npm i -g npm@latest

            - name: '🔧 Install dependencies'
              run: npm install

            - name: '🏗️ Build'
              run: npm run build

            - name: '🔧 Setup Pages'
              uses: actions/configure-pages@v3

            - name: '📦 Upload artifact'
              uses: actions/upload-pages-artifact@v2
              with:
                  path: './docs'

            - name: '🚀 Deploy to GitHub Pages'
              id: deployment
              uses: actions/deploy-pages@v2